/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package methods;

/**
 *
 * @author legsl_000
 */
public class MethodForm extends javax.swing.JFrame {

    /**
     * Creates new form MethodForm
     */
    public MethodForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput1 = new javax.swing.JTextField();
        txtInput2 = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnKill = new javax.swing.JButton();
        btnFormat = new javax.swing.JButton();
        btnInteger = new javax.swing.JButton();
        btnParseInt = new javax.swing.JButton();
        btnFindInt = new javax.swing.JButton();
        btnFindString = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInput1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input 1"));

        txtInput2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input 2"));

        lblResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        jLabel2.setText("CS-119 Lab 4 Methods");

        jLabel3.setText("Zane Neuschuler");

        btnKill.setText("Exit");
        btnKill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKillActionPerformed(evt);
            }
        });

        btnFormat.setText("Format");
        btnFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatActionPerformed(evt);
            }
        });

        btnInteger.setText("Is Integer");
        btnInteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegerActionPerformed(evt);
            }
        });

        btnParseInt.setText("Parse Int");
        btnParseInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParseIntActionPerformed(evt);
            }
        });

        btnFindInt.setText("Find Int");
        btnFindInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindIntActionPerformed(evt);
            }
        });

        btnFindString.setText("Find String");
        btnFindString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKill)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(214, 214, 214)
                        .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnFormat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFindInt)
                            .addComponent(btnParseInt)
                            .addComponent(btnFindString))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInteger)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFormat))
                .addGap(18, 18, 18)
                .addComponent(btnInteger)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnParseInt)
                        .addGap(18, 18, 18)
                        .addComponent(btnFindInt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFindString)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnKill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKillActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKillActionPerformed

    private void btnFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatActionPerformed
        // TODO:Test our formatnum function
        //input: read the text boxes
        float num = Float.parseFloat(txtInput1.getText() );
        String fmt = txtInput2.getText();
        
        //call or invoke our user defined formatNum() method
        String result = MyUtils.formatNum(num, fmt);
        
        
        //display result 
        
        lblResult.setText(result);
    }//GEN-LAST:event_btnFormatActionPerformed

    private void btnIntegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegerActionPerformed
        //read the text box
        String value = txtInput1.getText();
        
        //call our user function isInteger()
        boolean result = MyUtils.isInteger(value);
        
        //review ch 3 selection structures
        if (result)  {
            lblResult.setText("YES");
        }
        else{
            lblResult.setText("NO");
        }
    }//GEN-LAST:event_btnIntegerActionPerformed

    private void btnParseIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParseIntActionPerformed
        // read text box and convert to int using tryparseint
        int value = MyUtils.tryParseInt(txtInput1.getText(), 0);
        lblResult.setText(Integer.toString(value));
    }//GEN-LAST:event_btnParseIntActionPerformed

    private void btnFindIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindIntActionPerformed
        // declare
        final int [] numbers = {2, 15, 122, 82, 12, 44, 83};
        int value = MyUtils.tryParseInt(txtInput1.getText(), 0);
        
        //use finditems
        
        int result = MyUtils.findItem(numbers, value);
        if (result >= 0){
            lblResult.setText("Found! Subscript = " + Integer.toString(result));
        }
        else {
            lblResult.setText("Not found!");
        }
    }//GEN-LAST:event_btnFindIntActionPerformed

    private void btnFindStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStringActionPerformed
          // declare
        String [] numbers = {"cat", "DOG", "bird", "MOUSE", "human"};
        String value = txtInput1.getText();
        
        //use finditems
        
        int result = MyUtils.findItem(numbers, value);
        if (result >= 0){
            lblResult.setText("Found! Subscript = " + Integer.toString(result));
        }
        else {
            lblResult.setText("Not found!");
        }
    }//GEN-LAST:event_btnFindStringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MethodForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindInt;
    private javax.swing.JButton btnFindString;
    private javax.swing.JButton btnFormat;
    private javax.swing.JButton btnInteger;
    private javax.swing.JButton btnKill;
    private javax.swing.JButton btnParseInt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtInput1;
    private javax.swing.JTextField txtInput2;
    // End of variables declaration//GEN-END:variables
}
